-- =====================================================================
-- Sistema de Control de Inventario y Administracion de Alquiler de
-- Instrumentos Musicales - Base de datos UNIFICADA (PostgreSQL)
-- MODULO INVENTARIO Y TIENDAS (Matias): ciudades, tiendas, categorias,
--   subcategorias, marcas, instrumentos, mantenimientos
-- MODULO SEGURIDAD E IDENTIDAD (Ricardo): tipos_usuario, permisos,
--   tipo_usuario_permiso, usuarios, consentimientos, verificaciones_identidad,
--   intentos_fallidos, bitacora_auditoria
-- MODULO ALQUILERES (Leonardo): clientes, alquileres, actas, devoluciones,
--   tarifas_penalidad, penalidades, calificaciones
-- El script es idempotente: se puede ejecutar varias veces.
-- =====================================================================

CREATE TABLE IF NOT EXISTS ciudades (
    cod_ciudad      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_ciudad   VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS tiendas (
    cod_tienda          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_tienda       VARCHAR(100) NOT NULL UNIQUE,
    cod_ciudad          INT NOT NULL REFERENCES ciudades (cod_ciudad),
    direccion_tienda    TEXT,
    telefono_tienda     CHAR(8),
    latitud_tienda      DECIMAL(9,6) NOT NULL,
    longitud_tienda     DECIMAL(9,6) NOT NULL,
    responsable_tienda  VARCHAR(100),
    estado              CHAR(1) NOT NULL DEFAULT 'A' CHECK (estado IN ('A', 'I'))
);

CREATE TABLE IF NOT EXISTS categorias (
    cod_categoria     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_categoria  VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS subcategorias (
    cod_subcategoria     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_categoria        INT NOT NULL REFERENCES categorias (cod_categoria),
    nombre_subcategoria  VARCHAR(50) NOT NULL,
    UNIQUE (cod_categoria, nombre_subcategoria)
);

CREATE TABLE IF NOT EXISTS marcas (
    cod_marca     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_marca  VARCHAR(50) NOT NULL UNIQUE
);

-- Nota: cod_instrumento es VARCHAR(10) (y no CHAR(10)) porque en PostgreSQL
-- CHAR(n) rellena con espacios en blanco y el codigo saldria "INS-000001   ".
CREATE TABLE IF NOT EXISTS instrumentos (
    cod_instrumento      VARCHAR(10) PRIMARY KEY,
    nombre_instrumento   VARCHAR(100) NOT NULL,
    cod_subcategoria     INT NOT NULL REFERENCES subcategorias (cod_subcategoria),
    cod_marca            INT NOT NULL REFERENCES marcas (cod_marca),
    modelo_instrumento   VARCHAR(50) NOT NULL,
    cod_tienda           INT NOT NULL REFERENCES tiendas (cod_tienda),
    precio_alquiler      DECIMAL(7,2) NOT NULL CHECK (precio_alquiler > 0),
    estado_instrumento   VARCHAR(20) NOT NULL DEFAULT 'DISPONIBLE'
                         CHECK (estado_instrumento IN ('DISPONIBLE', 'ALQUILADO', 'EN MANTENIMIENTO')),
    fecha_registro       DATE NOT NULL DEFAULT CURRENT_DATE,
    estado               CHAR(1) NOT NULL DEFAULT 'A' CHECK (estado IN ('A', 'I'))
);

CREATE INDEX IF NOT EXISTS idx_instrumentos_tienda ON instrumentos (cod_tienda);
CREATE INDEX IF NOT EXISTS idx_instrumentos_subcategoria ON instrumentos (cod_subcategoria);
CREATE INDEX IF NOT EXISTS idx_instrumentos_estado ON instrumentos (estado_instrumento);

-- Secuencia para generar codigos automaticos: INS-001000, INS-001001, ...
CREATE SEQUENCE IF NOT EXISTS seq_cod_instrumento START WITH 1000;

CREATE TABLE IF NOT EXISTS mantenimientos (
    cod_mantenimiento     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_instrumento       VARCHAR(10) NOT NULL REFERENCES instrumentos (cod_instrumento),
    cod_devolucion        INT,
    id_usuario            INT,
    fecha_ingreso         DATE NOT NULL DEFAULT CURRENT_DATE,
    fecha_salida          DATE,
    descripcion_dano      TEXT NOT NULL,
    trabajo_realizado     TEXT,
    costo_reparacion      DECIMAL(7,2),
    estado_mantenimiento  VARCHAR(10) NOT NULL DEFAULT 'EN PROCESO'
                          CHECK (estado_mantenimiento IN ('EN PROCESO', 'CERRADO'))
);

CREATE INDEX IF NOT EXISTS idx_mantenimientos_instrumento ON mantenimientos (cod_instrumento);

-- =====================================================================
-- MODULO SEGURIDAD E IDENTIDAD (Ricardo)
-- =====================================================================

CREATE TABLE IF NOT EXISTS tipos_usuario (
    cod_tipo_usuario  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_tipo       VARCHAR(20) NOT NULL UNIQUE
                      CHECK (nombre_tipo IN ('ADMINISTRADOR', 'ENCARGADO', 'CLIENTE')),
    descripcion       VARCHAR(150)
);

CREATE TABLE IF NOT EXISTS permisos (
    cod_permiso     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_permiso  VARCHAR(50) NOT NULL UNIQUE,
    descripcion     VARCHAR(150)
);

CREATE TABLE IF NOT EXISTS tipo_usuario_permiso (
    cod_tipo_usuario  INT NOT NULL REFERENCES tipos_usuario (cod_tipo_usuario),
    cod_permiso       INT NOT NULL REFERENCES permisos (cod_permiso),
    PRIMARY KEY (cod_tipo_usuario, cod_permiso)
);

CREATE TABLE IF NOT EXISTS usuarios (
    id_usuario        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_tipo_usuario  INT NOT NULL REFERENCES tipos_usuario (cod_tipo_usuario),
    nombre_usuario    VARCHAR(50) NOT NULL UNIQUE,
    correo            VARCHAR(100) NOT NULL UNIQUE,
    password_hash     VARCHAR(100) NOT NULL,
    nombres           VARCHAR(80) NOT NULL,
    apellidos         VARCHAR(80) NOT NULL,
    cod_tienda        INT,
    activo            BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_registro    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Consentimiento informado previo a la captura biometrica (API en la semana 6).
CREATE TABLE IF NOT EXISTS consentimientos (
    id_consentimiento    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario           INT NOT NULL REFERENCES usuarios (id_usuario),
    tipo_consentimiento  VARCHAR(15) NOT NULL CHECK (tipo_consentimiento IN ('BIOMETRICO', 'DOCUMENTO')),
    aceptado             BOOLEAN NOT NULL,
    version_texto        VARCHAR(10) NOT NULL,
    ip_origen            VARCHAR(45),
    fecha_consentimiento TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Imagenes y datos del carnet se guardan CIFRADOS (BYTEA) con AES-256-GCM (semana 7).
CREATE TABLE IF NOT EXISTS verificaciones_identidad (
    id_verificacion     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario          INT NOT NULL REFERENCES usuarios (id_usuario),
    tipo_verificacion   VARCHAR(15) NOT NULL CHECK (tipo_verificacion IN ('FACE_LIVENESS', 'CARNET')),
    resultado           VARCHAR(10) NOT NULL CHECK (resultado IN ('APROBADA', 'RECHAZADA', 'PENDIENTE')),
    puntuacion          DECIMAL(5,2),
    imagen_cifrada      BYTEA,
    datos_cifrados      BYTEA,
    fecha_verificacion  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS intentos_fallidos (
    id_intento      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_usuario  VARCHAR(50) NOT NULL,
    ip_origen       VARCHAR(45),
    motivo          VARCHAR(100),
    fecha_intento   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_intentos_usuario_fecha ON intentos_fallidos (nombre_usuario, fecha_intento);

-- Bitacora de auditoria: registro INMUTABLE. Las reglas de abajo hacen que cualquier
-- UPDATE o DELETE sobre la tabla se ignore (solo se permite INSERT y SELECT).
CREATE TABLE IF NOT EXISTS bitacora_auditoria (
    id_bitacora     BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    fecha           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id_usuario      INT,
    nombre_usuario  VARCHAR(50),
    accion          VARCHAR(40) NOT NULL,
    entidad         VARCHAR(40),
    detalle         TEXT,
    ip_origen       VARCHAR(45)
);

CREATE INDEX IF NOT EXISTS idx_bitacora_fecha ON bitacora_auditoria (fecha);
CREATE INDEX IF NOT EXISTS idx_bitacora_accion ON bitacora_auditoria (accion);

CREATE OR REPLACE RULE bitacora_no_update AS ON UPDATE TO bitacora_auditoria DO INSTEAD NOTHING;
CREATE OR REPLACE RULE bitacora_no_delete AS ON DELETE TO bitacora_auditoria DO INSTEAD NOTHING;

-- =====================================================================
-- MODULO ALQUILERES (Leonardo)
-- =====================================================================

CREATE TABLE IF NOT EXISTS clientes (
    cod_cliente           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ci_cliente            VARCHAR(15) NOT NULL UNIQUE,
    nombres               VARCHAR(80) NOT NULL,
    apellidos             VARCHAR(80) NOT NULL,
    telefono              VARCHAR(15),
    correo                VARCHAR(100),
    direccion             TEXT,
    identidad_verificada  BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_registro        DATE NOT NULL DEFAULT CURRENT_DATE,
    estado                CHAR(1) NOT NULL DEFAULT 'A' CHECK (estado IN ('A', 'I'))
);

CREATE TABLE IF NOT EXISTS alquileres (
    cod_alquiler               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_cliente                INT NOT NULL REFERENCES clientes (cod_cliente),
    cod_instrumento            VARCHAR(10) NOT NULL REFERENCES instrumentos (cod_instrumento),
    fecha_alquiler             DATE NOT NULL DEFAULT CURRENT_DATE,
    fecha_devolucion_prevista  DATE NOT NULL,
    dias_alquiler              INT NOT NULL CHECK (dias_alquiler > 0),
    precio_dia                 DECIMAL(7,2) NOT NULL,
    monto_total                DECIMAL(9,2) NOT NULL,
    estado_alquiler            VARCHAR(10) NOT NULL DEFAULT 'ACTIVO'
                               CHECK (estado_alquiler IN ('ACTIVO', 'ATRASADO', 'DEVUELTO'))
);

CREATE INDEX IF NOT EXISTS idx_alquileres_instrumento ON alquileres (cod_instrumento);
CREATE INDEX IF NOT EXISTS idx_alquileres_cliente ON alquileres (cod_cliente);
CREATE INDEX IF NOT EXISTS idx_alquileres_estado ON alquileres (estado_alquiler);

-- El acta digital (PDF) se genera en la semana 5; la tabla queda lista desde ahora.
CREATE TABLE IF NOT EXISTS actas (
    cod_acta        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_alquiler    INT NOT NULL UNIQUE REFERENCES alquileres (cod_alquiler),
    fecha_emision   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ruta_pdf        VARCHAR(200),
    observaciones   TEXT
);

CREATE TABLE IF NOT EXISTS devoluciones (
    cod_devolucion         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_alquiler           INT NOT NULL UNIQUE REFERENCES alquileres (cod_alquiler),
    fecha_devolucion_real  DATE NOT NULL DEFAULT CURRENT_DATE,
    estado_conservacion    VARCHAR(10) NOT NULL
                           CHECK (estado_conservacion IN ('EXCELENTE', 'BUENO', 'REGULAR', 'DANADO')),
    observaciones          TEXT,
    dias_atraso            INT NOT NULL DEFAULT 0 CHECK (dias_atraso >= 0)
);

CREATE TABLE IF NOT EXISTS tarifas_penalidad (
    cod_tarifa      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_penalidad  VARCHAR(15) NOT NULL UNIQUE
                    CHECK (tipo_penalidad IN ('ATRASO', 'DANO_LEVE', 'DANO_GRAVE')),
    descripcion     VARCHAR(150) NOT NULL,
    tipo_calculo    VARCHAR(15) NOT NULL CHECK (tipo_calculo IN ('POR_DIA_ATRASO', 'MONTO_FIJO')),
    valor           DECIMAL(7,2) NOT NULL CHECK (valor >= 0),
    activa          BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS penalidades (
    cod_penalidad     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_devolucion    INT NOT NULL REFERENCES devoluciones (cod_devolucion),
    cod_tarifa        INT NOT NULL REFERENCES tarifas_penalidad (cod_tarifa),
    concepto          VARCHAR(150) NOT NULL,
    monto             DECIMAL(9,2) NOT NULL CHECK (monto >= 0),
    fecha_generacion  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_penalidades_devolucion ON penalidades (cod_devolucion);

-- La calificacion de la experiencia se registra en la semana 6; la tabla queda lista.
CREATE TABLE IF NOT EXISTS calificaciones (
    cod_calificacion     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_alquiler         INT NOT NULL UNIQUE REFERENCES alquileres (cod_alquiler),
    puntuacion           SMALLINT NOT NULL CHECK (puntuacion BETWEEN 1 AND 5),
    comentario           TEXT,
    fecha_calificacion   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- =====================================================================
-- ENLACES ENTRE MODULOS (integracion). "NOT VALID" = se exige desde ahora
-- en los registros nuevos y no revisa los que ya existian en tu base.
-- =====================================================================
ALTER TABLE usuarios DROP CONSTRAINT IF EXISTS fk_usuarios_tienda;
ALTER TABLE usuarios ADD CONSTRAINT fk_usuarios_tienda
    FOREIGN KEY (cod_tienda) REFERENCES tiendas (cod_tienda) NOT VALID;

ALTER TABLE mantenimientos DROP CONSTRAINT IF EXISTS fk_mantenimientos_usuario;
ALTER TABLE mantenimientos ADD CONSTRAINT fk_mantenimientos_usuario
    FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario) NOT VALID;

ALTER TABLE mantenimientos DROP CONSTRAINT IF EXISTS fk_mantenimientos_devolucion;
ALTER TABLE mantenimientos ADD CONSTRAINT fk_mantenimientos_devolucion
    FOREIGN KEY (cod_devolucion) REFERENCES devoluciones (cod_devolucion) NOT VALID;
