-- =====================================================================
-- Sistema de Control de Inventario y Administracion de Alquiler de
-- Instrumentos Musicales - Modulo Seguridad e Identidad (PostgreSQL)
-- Tablas: tipos_usuario, permisos, tipo_usuario_permiso, usuarios,
--         consentimientos, verificaciones_identidad, intentos_fallidos,
--         bitacora_auditoria
-- El script es idempotente: se puede ejecutar varias veces.
-- =====================================================================

CREATE TABLE IF NOT EXISTS tipos_usuario (
    cod_tipo_usuario  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_tipo       VARCHAR(20) NOT NULL UNIQUE
                      CHECK (nombre_tipo IN ('ADMINISTRADOR', 'ENCARGADO', 'CLIENTE')),
    descripcion       VARCHAR(150)
);

CREATE TABLE IF NOT EXISTS permisos (
    cod_permiso     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_permiso  VARCHAR(50) NOT NULL UNIQUE,
    descripcion     VARCHAR(150)
);

CREATE TABLE IF NOT EXISTS tipo_usuario_permiso (
    cod_tipo_usuario  INT NOT NULL REFERENCES tipos_usuario (cod_tipo_usuario),
    cod_permiso       INT NOT NULL REFERENCES permisos (cod_permiso),
    PRIMARY KEY (cod_tipo_usuario, cod_permiso)
);

CREATE TABLE IF NOT EXISTS usuarios (
    id_usuario        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_tipo_usuario  INT NOT NULL REFERENCES tipos_usuario (cod_tipo_usuario),
    nombre_usuario    VARCHAR(50) NOT NULL UNIQUE,
    correo            VARCHAR(100) NOT NULL UNIQUE,
    password_hash     VARCHAR(100) NOT NULL,
    nombres           VARCHAR(80) NOT NULL,
    apellidos         VARCHAR(80) NOT NULL,
    cod_tienda        INT,
    activo            BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_registro    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Consentimiento informado previo a la captura biometrica (API en la semana 6).
CREATE TABLE IF NOT EXISTS consentimientos (
    id_consentimiento    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario           INT NOT NULL REFERENCES usuarios (id_usuario),
    tipo_consentimiento  VARCHAR(15) NOT NULL CHECK (tipo_consentimiento IN ('BIOMETRICO', 'DOCUMENTO')),
    aceptado             BOOLEAN NOT NULL,
    version_texto        VARCHAR(10) NOT NULL,
    ip_origen            VARCHAR(45),
    fecha_consentimiento TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Imagenes y datos del carnet se guardan CIFRADOS (BYTEA) con AES-256-GCM (semana 7).
CREATE TABLE IF NOT EXISTS verificaciones_identidad (
    id_verificacion     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario          INT NOT NULL REFERENCES usuarios (id_usuario),
    tipo_verificacion   VARCHAR(15) NOT NULL CHECK (tipo_verificacion IN ('FACE_LIVENESS', 'CARNET')),
    resultado           VARCHAR(10) NOT NULL CHECK (resultado IN ('APROBADA', 'RECHAZADA', 'PENDIENTE')),
    puntuacion          DECIMAL(5,2),
    imagen_cifrada      BYTEA,
    datos_cifrados      BYTEA,
    fecha_verificacion  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS intentos_fallidos (
    id_intento      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_usuario  VARCHAR(50) NOT NULL,
    ip_origen       VARCHAR(45),
    motivo          VARCHAR(100),
    fecha_intento   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_intentos_usuario_fecha ON intentos_fallidos (nombre_usuario, fecha_intento);

-- Bitacora de auditoria: registro INMUTABLE. Las reglas de abajo hacen que cualquier
-- UPDATE o DELETE sobre la tabla se ignore (solo se permite INSERT y SELECT).
CREATE TABLE IF NOT EXISTS bitacora_auditoria (
    id_bitacora     BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    fecha           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id_usuario      INT,
    nombre_usuario  VARCHAR(50),
    accion          VARCHAR(40) NOT NULL,
    entidad         VARCHAR(40),
    detalle         TEXT,
    ip_origen       VARCHAR(45)
);

CREATE INDEX IF NOT EXISTS idx_bitacora_fecha ON bitacora_auditoria (fecha);
CREATE INDEX IF NOT EXISTS idx_bitacora_accion ON bitacora_auditoria (accion);

CREATE OR REPLACE RULE bitacora_no_update AS ON UPDATE TO bitacora_auditoria DO INSTEAD NOTHING;
CREATE OR REPLACE RULE bitacora_no_delete AS ON DELETE TO bitacora_auditoria DO INSTEAD NOTHING;
