-- =====================================================================
-- Sistema de Control de Inventario y Administracion de Alquiler de
-- Instrumentos Musicales - Modulo Inventario y Tiendas (PostgreSQL)
-- Tablas: ciudades, tiendas, categorias, subcategorias, marcas,
--         instrumentos, mantenimientos
-- El script es idempotente: se puede ejecutar varias veces.
-- =====================================================================

CREATE TABLE IF NOT EXISTS ciudades (
    cod_ciudad      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_ciudad   VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS tiendas (
    cod_tienda          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_tienda       VARCHAR(100) NOT NULL UNIQUE,
    cod_ciudad          INT NOT NULL REFERENCES ciudades (cod_ciudad),
    direccion_tienda    TEXT,
    telefono_tienda     CHAR(8),
    latitud_tienda      DECIMAL(9,6) NOT NULL,
    longitud_tienda     DECIMAL(9,6) NOT NULL,
    responsable_tienda  VARCHAR(100),
    estado              CHAR(1) NOT NULL DEFAULT 'A' CHECK (estado IN ('A', 'I'))
);

CREATE TABLE IF NOT EXISTS categorias (
    cod_categoria     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_categoria  VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS subcategorias (
    cod_subcategoria     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_categoria        INT NOT NULL REFERENCES categorias (cod_categoria),
    nombre_subcategoria  VARCHAR(50) NOT NULL,
    UNIQUE (cod_categoria, nombre_subcategoria)
);

CREATE TABLE IF NOT EXISTS marcas (
    cod_marca     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_marca  VARCHAR(50) NOT NULL UNIQUE
);

-- Nota: cod_instrumento es VARCHAR(10) (y no CHAR(10)) porque en PostgreSQL
-- CHAR(n) rellena con espacios en blanco y el codigo saldria "INS-000001   ".
CREATE TABLE IF NOT EXISTS instrumentos (
    cod_instrumento      VARCHAR(10) PRIMARY KEY,
    nombre_instrumento   VARCHAR(100) NOT NULL,
    cod_subcategoria     INT NOT NULL REFERENCES subcategorias (cod_subcategoria),
    cod_marca            INT NOT NULL REFERENCES marcas (cod_marca),
    modelo_instrumento   VARCHAR(50) NOT NULL,
    cod_tienda           INT NOT NULL REFERENCES tiendas (cod_tienda),
    precio_alquiler      DECIMAL(7,2) NOT NULL CHECK (precio_alquiler > 0),
    estado_instrumento   VARCHAR(20) NOT NULL DEFAULT 'DISPONIBLE'
                         CHECK (estado_instrumento IN ('DISPONIBLE', 'ALQUILADO', 'EN MANTENIMIENTO')),
    fecha_registro       DATE NOT NULL DEFAULT CURRENT_DATE,
    estado               CHAR(1) NOT NULL DEFAULT 'A' CHECK (estado IN ('A', 'I'))
);

CREATE INDEX IF NOT EXISTS idx_instrumentos_tienda ON instrumentos (cod_tienda);
CREATE INDEX IF NOT EXISTS idx_instrumentos_subcategoria ON instrumentos (cod_subcategoria);
CREATE INDEX IF NOT EXISTS idx_instrumentos_estado ON instrumentos (estado_instrumento);

-- Secuencia para generar codigos automaticos: INS-001000, INS-001001, ...
CREATE SEQUENCE IF NOT EXISTS seq_cod_instrumento START WITH 1000;

-- cod_devolucion e id_usuario todavia no tienen clave foranea porque las tablas
-- devoluciones (modulo Alquileres) y usuarios (modulo Seguridad) las desarrollan
-- otros integrantes. Se enlazaran al integrar los modulos.
CREATE TABLE IF NOT EXISTS mantenimientos (
    cod_mantenimiento     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_instrumento       VARCHAR(10) NOT NULL REFERENCES instrumentos (cod_instrumento),
    cod_devolucion        INT,
    id_usuario            INT,
    fecha_ingreso         DATE NOT NULL DEFAULT CURRENT_DATE,
    fecha_salida          DATE,
    descripcion_dano      TEXT NOT NULL,
    trabajo_realizado     TEXT,
    costo_reparacion      DECIMAL(7,2),
    estado_mantenimiento  VARCHAR(10) NOT NULL DEFAULT 'EN PROCESO'
                          CHECK (estado_mantenimiento IN ('EN PROCESO', 'CERRADO'))
);

CREATE INDEX IF NOT EXISTS idx_mantenimientos_instrumento ON mantenimientos (cod_instrumento);
